MxOnline/MxOnline/urls.py
import xadmin

from django.conf.urls import url, include
from django.views.generic import TemplateView  # 处理模板文件的返回
from django.views.static import serve  # 处理上传文件的访问

from MxOnline.settings import MEDIA_ROOT
from users.views import IndexView

urlpatterns = [
    # path('xadmin/', xadmin.site.urls)
    url(r'xadmin/', xadmin.site.urls),  # xadmin后台管理
    url(r'^captcha/', include('captcha.urls')),  # 图片验证码

    # url(r'^$', TemplateView.as_view(template_name="index.html"), name="index"),
    url(r'^$', IndexView.as_view(), name="index"),

    # 用户URL
    url(r'^users/', include(('users.urls', "users"), namespace="users")),

    # 课程机构url
    url(r'^org/', include(('organization.urls', "organization"), namespace="org")),

    # 课程相关url
    url(r'^course/', include(('courses.urls', "courses"), namespace="course")),

    # 处理上传文件的访问(document_root,为处理函数的参数，意为该url下的文件到哪里去找
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),

    # 静态文件
    # url(r'^static/(?P<path>.*)$', serve, {"document_root": STATIC_ROOT}),

]

# 全局 404 页面配置
handler404 = 'users.views.page_not_found'
handler500 = 'users.views.page_error'


MxOnline/apps/courses/urls.py
# coding: utf-8
from django.conf.urls import url, include

from courses.views import CourseListView, CourseDetailView, CourseInfoView, CommentsView, AddCommentsView, VideoPlayView

urlpatterns = [
    url(r'^list/$', CourseListView.as_view(), name="course_list"),  # 课程列表页
    url(r'^detail/(?P<course_id>\d+)$', CourseDetailView.as_view(), name="course_detail"),  # 课程详情页
    url(r'^info/(?P<course_id>\d+)$', CourseInfoView.as_view(), name="course_info"),  # 课程章节视频页
    url(r'^comment/(?P<course_id>\d+)$', CommentsView.as_view(), name="course_comments"),  # 课程评论页
    url(r'^add_comment/$', AddCommentsView.as_view(), name="add_comment"),  # 添加课程评论
    url(r'^video/(?P<video_id>\d+)/$', VideoPlayView.as_view(), name='video_play'),  # 播放视频
]

MxOnline/apps/organization/urls.py
from django.conf.urls import url, include

from organization.views import OrgView, AddUserAskView, OrgHomeView, OrgCourseView, OrgDescView, OrgTeacherView,AddFavView,TeacherListView,TeacherDetailView

urlpatterns = [
    url(r'^list/$', OrgView.as_view(), name="org_list"),  # 课程机构列表页
    url(r'^add_ask/$', AddUserAskView.as_view(), name="add_ask"),  # 咨询栏提交
    url(r'^home/(?P<org_id>\d+)/$', OrgHomeView.as_view(), name="org_home"),  # 机构首页
    url(r'^course/(?P<org_id>\d+)/$', OrgCourseView.as_view(), name="org_course"),  # 机构课程
    url(r'^desc/(?P<org_id>\d+)/$', OrgDescView.as_view(), name="org_desc"),  # 机构课程介绍
    url(r'^org_teacher/(?P<org_id>\d+)/$', OrgTeacherView.as_view(), name="org_teacher"),  # 机构教师页
    url(r'^add_fav/$', AddFavView.as_view(), name="add_fav"),  # 机构收藏

    url(r'^teacher/list/$', TeacherListView.as_view(), name='teacher_list'),  # 讲师列表页
    url(r'^teacher/detail/(?P<teacher_id>\d+)/$', TeacherDetailView.as_view(), name='teacher_detail'),  # 讲师详情页

]

MxOnline/apps/users/urls.py
from django.conf.urls import url, include

from users.views import LoginView, RegisterView, ActivateUserView, ForgetPwdView, ResetView, ModifyPwdView, \
    UserInfoView, LogoutView, UploadImageView, UpdatePwdView, SendEmailCodeView, UpdateEmailView, MyCourseView, \
    MyFavOrgView, MyFavTeacherView, MyFavCourseView, MyMessageView

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name="login"),  # 登录 # 根目录匹配的时候是不需要“/”的所以要把/login/的“/”去掉
    url(r'^register/$', RegisterView.as_view(), name="register"),  # 注册
    url(r'^activate/(?P<activate_code>.*)$', ActivateUserView.as_view(), name="user_activate"),  # 激活
    url(r'^forget/$', ForgetPwdView.as_view(), name="forget_pwd"),  # 返回找回密码页面
    url(r'^reset/(?P<reset_code>.*)$', ResetView.as_view(), name="reset_pwd"),  # 找回密码
    url(r'^modify/$', ModifyPwdView.as_view(), name="modify_pwd"),  # 处理找回密码逻辑

    url(r'^logout/$', LogoutView.as_view(), name='logout'),  # 退出登录
    url(r'^info/$', UserInfoView.as_view(), name="user_info"),  # 用户信息页及信息页个人资料修改
    url(r'^image/upload/$', UploadImageView.as_view(), name='image_upload'),  # 用户头像修改
    url(r'^update/pwd/$', UpdatePwdView.as_view(), name='update_pwd'),  # 用户个人中心修改密码
    url(r'^sendemail_code/$', SendEmailCodeView.as_view(), name='sendemail_code'),  # 修改邮箱时 发送邮箱验证码
    url(r'^update_email/$', UpdateEmailView.as_view(), name='update_email'),  # 修改邮箱时，验证邮箱和验证码
    url(r'^mycourse/$', MyCourseView.as_view(), name='mycourse'),  # 我的课程
    url(r'^myfav/org/$', MyFavOrgView.as_view(), name='myfav_org'),  # 我收藏的课程机构
    url(r'^myfav/teacher/$', MyFavTeacherView.as_view(), name='myfav_teacher'),  # 我收藏的授课讲师
    url(r'^myfav/course/$', MyFavCourseView.as_view(), name='myfav_course'),  # 我收藏的课程
    url(r'^mymessage/$', MyMessageView.as_view(), name='mymessage'),  # 我的消息

]


MxOnline/apps/users/forms.py
# coding: utf-8
from django import forms
from captcha.fields import CaptchaField

from users.models import UserProfile


class LoginFrom(forms.Form):
    '''登录表单'''
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, min_length=5)


class RegisterForm(forms.Form):
    '''注册表单'''
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True, min_length=5)
    # raise ValidationError(getattr(self, 'error_messages', {}).get('invalid', ugettext_lazy('Invalid CAPTCHA')))
    captcha = CaptchaField(error_messages={"invalid": "验证码错误"})


class ForgetForm(forms.Form):
    '''找回密码'''
    email = forms.EmailField(required=True)
    captcha = CaptchaField(error_messages={"invalid": "验证码错误"})


class ModifyPwdForm(forms.Form):
    '''密码修改'''
    password1 = forms.CharField(required=True, min_length=5)
    password2 = forms.CharField(required=True, min_length=5)


class UploadImageForm(forms.ModelForm):
    """头像上传"""

    class Meta:
        model = UserProfile
        fields = ['image']


class UserInfoForm(forms.ModelForm):
    """用户个人信息页(保存)"""

    class Meta:
        model = UserProfile
        fields = ['nick_name', 'gender', 'birday', 'address', 'mobile']

MxOnline/templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %}慕学在线首页{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block custom_css %}{% endblock custom_css %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
</head>
<body>
<section class="headerwrap ">
    <header>
        <div class=" header">
            <div class="top">
                <div class="wp">
                    <div class="fl"><p>服务电话：<b>33333333</b></p></div>
                    <!--登录后跳转-->

                    {% if request.user.is_authenticated %}
                        <div class="personal">
                            <dl class="user fr">
                                <dd>{{ request.user.username }}<img class="down fr"
                                                                    src="{% static 'images/top_down.png' %}"/></dd>
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                            </dl>
                            <div class="userdetail">
                                <dl>
                                    <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}"/>
                                    </dt>
                                    <dd>
                                        <h2>{{ request.user.nick_name }}</h2>
                                        <p>{{ request.user.username }}</p>
                                    </dd>
                                </dl>
                                <div class="btn">
                                    <a class="personcenter fl" href="{% url 'users:user_info' %}">进入个人中心</a>
                                    <a class="fr" href="{% url 'users:logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'users:mymessage' %}">
                            <div class="msg-num">
                                <span id="MsgNum">{{ request.user.get_unread_nums }}</span>
                            </div>
                        </a>
                    {% else %}
                        <a style="color:white" class="fr registerbtn" href="{% url 'users:register' %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'users:login' %}">登录</a>
                    {% endif %}

                </div>
            </div>

            <div class="middle">
                <div class="wp">
                    <a href="{% url 'index' %}"><img class="fl" src="{% static 'images/logo.jpg' %}"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">公开课</li>
                                <li data-value="org">课程机构</li>
                                <li data-value="teacher">授课老师</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
                    </div>
                </div>
            </div>


            <nav>
                <div class="nav">
                    <div class="wp">
                        <ul>
                            <li {% if request.path == '/' %}class="active"{% endif %}><a href="{% url 'index' %}">首页</a></li>
                            {#                            取前url前六位#}
                            <li {% if request.path|slice:'7' == '/course' %}class="active"{% endif %}>
                                <a href="{% url 'course:course_list' %}">
                                    公开课<img class="hot" src="{% static 'images/nav_hot.png' %}">
                                </a>
                            </li>
                            <li {% if request.path|slice:'12' == '/org/teacher' %}class="active"{% endif %}>
                                <a href="{% url 'org:teacher_list' %}">授课教师</a>
                            </li>
                            <li {% if request.path|slice:'9' == '/org/list' %}class="active"{% endif %}><a
                                    href="{% url 'org:org_list' %}">授课机构</a></li>
                        </ul>
                    </div>
                </div>
            </nav>

        </div>
    </header>
</section>
<!--crumbs start-->
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                {#                <li>课程机构</li>#}
            </ul>
        </div>
    </section>
{% endblock custom_bread %}
{% block content %}

{% endblock content %}
<footer>
    <div class="footer">
        <div class="wp">
            <ul class="cont">
                <li class="logo"><a href=""><img src="{% static 'images/footlogo.png' %}"/></a></li>
                <li class="code"><img src="{% static 'images/code.jpg' %}"/>
                    <p class="center">扫描关注微信</p></li>
                <li class="third"><img class="fl" src="{% static 'images/tell.png' %}"/>
                    <p class="tell">33333333</p>
                    <p class="time">周一至周日 9:00-18:00</p></li>
            </ul>

        </div>
        <p class="line"></p>
        <div class="wp clear">
            <span class="fl">? 2019 www.projectsedu.com 慕学在线-在线学习交流平台 保留所有权利</span>
            <span class="fr">copyright ? 2019 ICP备案证书号：蜀ICP备xxxxx号-1</span>
        </div>
    </div>
</footer>

<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}" type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}" type="text/javascript"></script>
{% block custom_js %}

{% endblock custom_js %}
</body>
</html>

MxOnline/templates/org-detail-desc.html
{% extends 'org_base.html' %}
{% block title %}机构介绍{% endblock title %}
{% block page_path %}机构介绍{% endblock page_path %}
{% block right_form %}

        <div class="right companycenter layout" >
        <div class="head">
            <h1>机构介绍</h1>
        </div>
        <div class="des">

            <p>{{ course_org.desc }}</p>
        </div>
    </div>

{% endblock right_form %}




MxOnline/templates/usercenter-base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
  <meta charset="UTF-8">
  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <title>{% block title %}个人信息- 慕学在线网{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/reset.css' %}">
  <link rel="stylesheet" href="{% static 'css/animate.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">

  <link rel="stylesheet" href="{% static 'css/lq.datetimepick.css' %}"/>

  {% block custom_css %}
  {% endblock %}
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}"></script>

</head>
<body>
<section class="headerwrap headerwrap2">
  <header>
    <div class=" header header2">
      <div class="top">
        <div class="wp">
          <div class="fl"><p>服务电话：<b>33333333</b></p></div>
          <!--登录后跳转-->
          {% if request.user.is_authenticated %}
            <div class="personal">
              <dl class="user fr">
                <dd>{{ request.user.nick_name }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
              </dl>
              <div class="userdetail">
                <dl>
                  <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}" /></dt>
                  <dd>
                    <h2>{{ request.user.nick_name }}</h2>
                    <p>{{ request.user.username }}</p>
                  </dd>
                </dl>
                <div class="btn">
                  <a class="personcenter fl" href="{% url 'users:user_info' %}">进入个人中心</a>
                  <a class="fr" href="{% url 'users:logout' %}">退出</a>
                </div>
              </div>
            </div>
            <a href="{% url 'users:mymessage' %}">
              <div class="msg-num">
                <span id="MsgNum">{{ request.user.get_unread_nums }}</span>
              </div>
            </a>
          {% else %}
            <a style="color:white" class="fr registerbtn" href="{% url ':users:register' %}">注册</a>
            <a style="color:white" class="fr loginbtn" href="{% url 'users:login' %}">登录</a>
          {% endif %}

        </div>
      </div>

      <div class="middle">
        <div class="wp">
          <a href="{% url 'index' %}"><img class="fl" src="{% static 'images/logo.jpg' %}"/></a>
          <div class="searchbox fr">
            <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
              <ul class="selectMenu" id="jsSelectMenu">
                <li data-value="course">公开课</li>
                <li data-value="org">课程机构</li>
                <li data-value="teacher">授课老师</li>
              </ul>
            </div>
            <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
            <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
          </div>
        </div>
      </div>


      <nav>
        <div class="nav">
          <div class="wp">
            <ul>
              <li class="{% ifequal request.path '/' %}active{% endifequal %}"><a href="{% url 'index' %}">首页</a></li>
              <li class="{% ifequal request.path|slice:'7' '/course' %}active{% endifequal %}">
                <a href="{% url 'courses:course_list' %}">
                  公开课<img class="hot" src="{% static 'images/nav_hot.png' %}">
                </a>
              </li>
              <li class="{% ifequal request.path|slice:'17' '/org/teacher/list' %}active{% endifequal %}">
                <a href="{% url 'org:teacher_list' %}">授课教师</a>
              </li>
              <li class="{% ifequal request.path|slice:'9' '/org/list' %}active{% endifequal %}"><a href="{% url 'org:org_list' %}">授课机构</a></li>
            </ul>
          </div>
        </div>
      </nav>

    </div>
  </header>
</section>


<!--crumbs start-->
{% block custom_bread %}
<section>
  <div class="wp">
    <ul class="crumbs">
      <li><a href="{% url 'index' %}">首页</a>></li>
      <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
      <li>个人信息</li>
    </ul>
  </div>
</section>
{% endblock %}

<section>
  <div class="wp list personal_list">
    <div class="left">
      <ul>
        <li {% if request.path|slice:'12' == '/users/info/' %}class="active2"{% endif %} ><a href="{% url 'users:user_info' %}">个人资料</a></li>
        <li {% if request.path|slice:'16' == '/users/mycourse/' %}class="active2"{% endif %} ><a href="{% url 'users:mycourse' %}">我的课程</a></li>
        <li {% if request.path|slice:'17' == '/users/myfav/org/' %}class="active2"{% endif %} ><a href="{% url 'users:myfav_org' %}">我的收藏</a></li>
        <li {% if request.path|slice:'17' == '/users/mymessage/' %}class="active2"{% endif %} >
          <a href="{% url 'users:mymessage' %}" style="position: relative;">
            我的消息
          </a>
        </li>
      </ul>
    </div>

    {% block right_content %}
    {% endblock %}

  </div>
</section>


<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}"></script>
<script src="{% static 'js/unslider.js' %}"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"></script>
<script src="{% static 'js/validateDialog.js' %}"></script>
<script src="{% static 'js/deco-common.js' %}"></script>

<script src='{% static 'js/plugins/jquery.upload.js' %}' type='text/javascript'></script>
<script src="{% static 'js/validate.js' %}"></script>
<script src="{% static 'js/deco-user.js' %}"></script>

{% block custom_js %}
{% endblock %}

<script>
  // 课程取消收藏
  $('.jsDeleteFav_course').on('click', function () {
    var _this = $(this),
      favid = _this.attr('data-favid');
    $.ajax({
      cache: false,
      type: "POST",
      url: "{% url 'org:add_fav' %}",
      data: {
        fav_type: 1,
        fav_id: favid,
        csrfmiddlewaretoken: "{{ csrf_token }}",
      },
      async: true,
      success: function (data) {
        Dml.fun.winReload();
      }
    });
  });

  $('.jsDeleteFav_teacher').on('click', function () {
    var _this = $(this),
      favid = _this.attr('data-favid');
    $.ajax({
      cache: false,
      type: "POST",
      url: "{% url 'org:add_fav' %}",
      data: {
        fav_type: 3,
        fav_id: favid,
        csrfmiddlewaretoken: "{{ csrf_token }}",
      },
      async: true,
      success: function (data) {
        Dml.fun.winReload();
      }
    });
  });


  $('.jsDeleteFav_org').on('click', function () {
    var _this = $(this),
      favid = _this.attr('data-favid');
    $.ajax({
      cache: false,
      type: "POST",
      url: "{% url 'org:add_fav' %}",
      data: {
        fav_type: 2,
        fav_id: favid,
        csrfmiddlewaretoken: "{{ csrf_token }}",
      },
      async: true,
      success: function (data) {
        Dml.fun.winReload();
      }
    });
  });
</script>


<script>
  var shareUrl = '',
    shareText = '',
    shareDesc = '',
    shareComment = '';
  $(function () {
    $(".bdsharebuttonbox a").mouseover(function () {
      var type = $(this).attr('data-cmd'),
        $parent = $(this).parent('.bdsharebuttonbox'),
        fxurl = $parent.attr('data-url'),
        fxtext = $parent.attr('data-text'),
        fxdesc = $parent.attr('data-desc'),
        fxcomment = $parent.attr('data-comment');
      switch (type) {
        case 'tsina':
        case 'tqq':
        case 'renren':
          shareUrl = fxurl;
          shareText = fxdesc;
          shareDesc = '';
          shareComment = '';
          break;
        default :
          shareUrl = fxurl;
          shareText = fxtext;
          shareDesc = fxdesc;
          shareComment = fxcomment;
          break;
      }
    });
  });
  function SetShareUrl(cmd, config) {
    if (shareUrl) {
      config.bdUrl = "" + shareUrl;
    }
    if (shareText) {
      config.bdText = shareText;
    }
    if (shareDesc) {
      config.bdDesc = shareDesc;
    }
    if (shareComment) {
      config.bdComment = shareComment;
    }

    return config;
  }
  window._bd_share_config = {
    "common": {
      "onBeforeClick": SetShareUrl,
      "bdPic": "",
      "bdMini": "2",
      "searchPic": "1",
      "bdMiniList": false
    },
    "share": {
      "bdSize": "16"
    }
  };
  with (document)0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = 'http://bdimg.share.baidu.com{% static '' %}api/js/share.js?v=89860593.js?cdnversion=' + ~(-new Date() / 36e5)];
</script>
</body>
</html>

MxOnline/templates/usercenter-fav-course.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}
{% block title %}我的课程-慕学在线网{% endblock %}

{% block custom_bread %}
<section>
  <div class="wp">
    <ul class="crumbs">
      <li><a href="{% url 'index' %}">首页</a>></li>
      <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
      <li>我的收藏</li>
    </ul>
  </div>
</section>
{% endblock %}

{% block right_content %}
<div class="right">
      <div class="personal_des Releasecont">
        <div class="head">
          <h1>我的收藏</h1>
        </div>
      </div>
      <div class="personal_des permessage">
        <div class="head">
          <ul class="tab_header messagehead">
            <li><a href="{% url 'users:myfav_org' %}">课程机构</a></li>
            <li><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
            <li class="active"><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
          </ul>

        </div>
        <div class="companycenter">
          <div class="group_list brief">
            {% for fav_course in course_list %}
            <div class="module1_5 box">
              <a href="{% url 'courses:course_detail' fav_course.id %}">
                <img width="214" height="190"
                     src="{{ MEDIA_URL }}{{ fav_course.image }}"/>
              </a>
              <div class="des">
                <a href="{% url 'courses:course_detail' fav_course.id %}"><h2>{{ fav_course.name }}</h2></a>
                <span class="fl">时长：<i class="key">{{ fav_course.learn_times }}</i></span>
                <span class="fr">学习人数：{{ fav_course.students }}</span>
              </div>
              <div class="bottom">
                <span class="fl">{{ fav_course.course_org.name }}</span>
                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ fav_course.id }}"></span>
              </div>
            </div>
            {% endfor %}

          </div>
        </div>
      </div>
    </div>
{% endblock %}

MxOnline/templates/usercenter-fav-org.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}
{% block title %}我的课程-慕学在线网{% endblock %}

{% block custom_bread %}
<section>
  <div class="wp">
    <ul class="crumbs">
      <li><a href="{% url 'index' %}">首页</a>></li>
      <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
      <li>我的收藏</li>
    </ul>
  </div>
</section>
{% endblock %}

{% block right_content %}
<div class="right">
      <div class="personal_des Releasecont">
        <div class="head">
          <h1>我的收藏</h1>
        </div>

      </div>
      <div class="personal_des permessage">
        <div class="head">
          <ul class="tab_header messagehead">
            <li class="active"><a href="{% url 'users:myfav_org' %}">课程机构</a></li>
            <li><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
            <li><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
          </ul>
        </div>
        <div class="messagelist">
          {% for org in org_list %}
          <div class="messages butler_list company company-fav-box">
            <dl class="des fr">
              <dt>
                <a href="{% url 'org:org_home' org.id %}">
                  <img width="160" height="90" src="{{ MEDIA_URL }}{{ org.image }}"/>
                </a>
              </dt>
              <dd>
                <h1><a href="{% url 'org:org_home' org.id %}">{{ org.name }}</a></h1>
                <div class="pic fl" style="width:auto;">
                  <img src="{% static 'images/authentication.png' %}"/>
                  <img src="{% static 'images/gold.png' %}"/>
                </div>
                <span class="c8 clear">{{ org.address }}</span>
                <div class="delete jsDeleteFav_org" data-favid="{{ org.id }}"></div>
              </dd>
            </dl>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
{% endblock %}